baseurl = "https://gavin-sun555.github.io/"
title = "YAN"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
preserveTaxonomyNames = true
hasCJKLanguage = true

[services]
  # Enable comments by entering your Disqus shortname
  [services.disqus]
    shortname = "https-gavin-sun555-github-io"
  [services.googleAnalytics]
    id = ""

[pagination]
  pagerSize = 5 # frontpage pagination

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/home-bg.jpg"
  SEOTitle = "Yan Blog"
  description = "Software Developer, and World Traveler"
  keyword = ""
  slogan = ""
  upstreamAttribution = true

  image_404 = "img/404-bg.jpg"
  title_404 = "Not Found :("
  omit_categories = false

  # leancloud storage for page view counter
  page_view_counter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = true
  algolia_appId = "8FTF2IUFX8"
  algolia_indexName = "algolia"
  algolia_apiKey = "ea697c1c06eb948986928c3741fafe8b"

  # Sidebar settings
  sidebar_about_description = "Software Developer"
  #sidebar_avatar = ""      # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_avatar = ""      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 1 


  disqus_site = ""




  friends = false
  bookmarks = false
  about_me = true

  # Include any custom CSS and/or JS files, url or relative to /static folder
  #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  [params.social]
  rss            = true 
  email          = "gavin.yansu@gmail.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  linkedin       = "https://www.linkedin.com/in/yan-sun-743898193"
#  stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/Gavin-Sun555"
#  wechat         = "your wechat qr code image"
  #medium        = "full profile url in medium"
  #slack         = "full workspace url in slack"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  #gitlab        = "full profile url in gitlab"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #xing          = "https://www.xing.com/profile/yourxingid"
  #git           = "full profile url for git user"


  [[params.additional_menus]]
  title =  "portfolio"
  href =  "/portfolio/"

  [[params.additional_menus]]
  title =  "ARCHIVE"
  href =  "/archive/"

  [[params.additional_menus]]
  title =  "ABOUT"
  href =  "/about/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
